# Generated by Django 4.1.7 on 2023-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloded', models.IntegerField(default=0)),
                ('seen', models.IntegerField(default=0)),
                ('configdata', models.TextField()),
                ('ipdata', models.GenericIPAddressField()),
                ('file', models.FileField(upload_to='media/')),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
            ],
        ),
    ]
