# Generated by Django 4.1.7 on 2023-02-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loadFile', '0002_alter_files_downloded_alter_files_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='downloded',
            field=models.IntegerField(default=0),
        ),
    ]
