# Generated by Django 4.1.7 on 2023-02-23 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loadFile', '0003_files_userid_alter_files_downloded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
