# Generated by Django 4.1.7 on 2023-02-23 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0004_alter_files_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadFile.files'),
        ),
    ]
