# Generated by Django 3.2.16 on 2023-03-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0006_alter_files_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
