# Generated by Django 4.1.7 on 2023-04-30 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loadFile', '0011_datacounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exist_before', models.DateTimeField()),
                ('seen_user', models.IntegerField(default=0)),
                ('web_see', models.BooleanField(default=False)),
                ('user_see_client', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='loadFile.files')),
                ('looking_see_users', models.ManyToManyField(related_name='file_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
