# Generated by Django 4.1.7 on 2023-05-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0012_fileaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileaccess',
            old_name='file',
            new_name='fileid',
        ),
    ]
