# Generated by Django 4.1.7 on 2023-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0013_rename_file_fileaccess_fileid'),
    ]

    operations = [
        migrations.CreateModel(
            name='renderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('file_link', models.FileField(upload_to='media/')),
                ('fileid', models.ManyToManyField(to='loadFile.files')),
            ],
        ),
    ]
