# Generated by Django 4.1.7 on 2023-05-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0014_renderdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileaccess',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='fileaccess',
            old_name='exist_before',
            new_name='existBefore',
        ),
        migrations.RenameField(
            model_name='fileaccess',
            old_name='looking_see_users',
            new_name='lookingSeeUsers',
        ),
        migrations.RenameField(
            model_name='fileaccess',
            old_name='seen_user',
            new_name='seenUser',
        ),
        migrations.RenameField(
            model_name='fileaccess',
            old_name='user_see_client',
            new_name='userSeeClient',
        ),
        migrations.RenameField(
            model_name='fileaccess',
            old_name='web_see',
            new_name='webSee',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='renderdata',
            old_name='file_link',
            new_name='fileLink',
        ),
    ]
