# Generated by Django 4.1.7 on 2023-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0015_rename_created_at_fileaccess_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='existBefore',
            field=models.DateTimeField(null=True),
        ),
    ]
