# Generated by Django 4.1.7 on 2023-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadFile', '0016_alter_fileaccess_amount_alter_fileaccess_existbefore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderdata',
            name='fileLink',
            field=models.CharField(max_length=500),
        ),
    ]
