# Generated by Django 4.1.7 on 2023-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_idphone_devid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idphone',
            name='devid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
