# Generated by Django 4.1.7 on 2023-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=100)),
                ('link', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
