# Generated by Django 4.1.7 on 2023-05-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
