# Generated by Django 4.1.7 on 2023-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_photo_photo_alter_photo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='media/users/mainphoto/user.jpg', upload_to='media/users/mainphoto/'),
        ),
    ]
